#!/bin/sh

set -e

cd $(dirname $0)

if [ ! -d fronter-git ] ; then
    mkdir fronter-git
    (cd fronter-git; git init)
fi

cd fronter-git ; ../fetch-fronter-data

tmpfile="$(tempfile)"
if git commit -m "Update raw HTML data." *.html > $tmpfile 2>&1 ; then
    cat $tmpfile
    git add *.txt
    git diff HEAD
    git commit -m "Update information."
fi
rm $tmpfile
